### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by schwatter** [johsam/timebox-evo-rest#1]
Hello,

i tried it at my raspi. But i get this error:

`root@pi-zero-w1:/opt/fhem/tera# python tb-evo-rest.py
  File "tb-evo-rest.py", line 39
    def after_delay(self, delay: int, fn: Callable):
                               ^
SyntaxError: invalid syntax
root@pi-zero-w1:/opt/fhem/tera#`

I installed latest python3

`root@pi-zero-w1:/opt/fhem/tera# python3
Python 3.8.0a3 (default, Apr 25 2019, 19:40:59)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.`

and also tornado

`root@pi-zero-w1:/opt/fhem/tera# apt-get install python3-tornado
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-tornado is already the newest version (4.4.3-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root@pi-zero-w1:/opt/fhem/tera#`

**Comment by schwatter** [comment]
Ah forget it... i wrote python instead python3...

**Comment by schwatter** [comment]
Ok, after set up PILLOW i hang on this:

`root@pi-zero-w1:/opt/fhem/tera# python3 tb-evo-rest.py
Traceback (most recent call last):
  File "tb-evo-rest.py", line 379, in <module>
    main()
  File "tb-evo-rest.py", line 363, in main
    application = Application()
  File "tb-evo-rest.py", line 84, in __init__
    self._divoom = Divoom()
  File "tb-evo-rest.py", line 28, in __init__
    self._timebox = Timebox(options.address, True)
  File "/opt/fhem/tera/evo/timebox.py", line 12, in __init__
    self.sock = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket.BTPROTO_RFCOMM)
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
root@pi-zero-w1:/opt/fhem/tera#`

Any hint for setup AF_BLUETOOTH correct?

**Comment by schwatter** [comment]
Ok, now i get it.
I changed from python sockets to pybluez

`import socket
import binascii
import logging
import bluetooth

class Timebox:
    debug = False

    def __init__(self, addr, debug=False):
        self.debug = debug

        self.sock = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
        self.addr = addr

    def connect(self):
        self.sock.connect((self.addr, 1))

    def disconnect(self):
        self.sock.close()

    def send(self, package):
        if self.debug:
            print([hex(b)[2:].zfill(2) for b in package])
        self.sock.send(str(bytearray(package)))

    def send_raw(self, bts):
        # print('Send:', binascii.hexlify(bts))
        self.sock.send(bts)
        ret = self.sock.recv(256)
        logging.info('Received: 0x' + str(binascii.hexlify(ret), 'utf-8'))
`

**Comment by johsam** [comment]
Good, Did you get it to work ?
I will add some documentaion the next few days.

**Comment by schwatter** [comment]
Yes, all is working as provided.
I think my problem with python3 is, that i have to build it with bluetooth sockets.

https://github.com/ContinuumIO/anaconda-issues/issues/1035

But my second testsystem is some raspizero. So switching to pybluez was the fastest option.
